import { Hero, Panel } from "@skillforge/ui";
import { SiteShell } from "../../../components/site-shell";

export default function ContributingPage() {
  return (
    <SiteShell>
      <Hero
        kicker="Contributing"
        title="The repo welcomes contributions. It does not lower the bar for them."
        subtitle="Skillforge accepts code, content, benchmark, and docs work, but it is explicitly hostile to maturity inflation, fake certainty, prompt-dump writing, and shallow benchmark theater."
      />
      <div className="sf-grid sf-grid-3" style={{ marginTop: 24 }}>
        <Panel>
          <h2>What gets merged faster</h2>
          <p>Changes that improve real workflow value, sharpen weak copy, or reduce ambiguity without expanding claims the repo cannot support.</p>
        </Panel>
        <Panel>
          <h2>What gets pushed back</h2>
          <p>Generic content, maturity inflation, fake compatibility framing, and any contribution that makes the library look bigger at the cost of trust.</p>
        </Panel>
        <Panel>
          <h2>What maintainers look for</h2>
          <p>Clear triggers, structured outputs, realistic examples, meaningful tests, and wording that sounds like a maintained tool rather than a generated prompt pack.</p>
        </Panel>
      </div>
      <Panel style={{ marginTop: 24 }}>
        <h2>Contribution flow</h2>
        <ol>
          <li>Update `data/skill-seeds.json` or deepen a generated Skill.</li>
          <li>Regenerate the library and the catalog.</li>
          <li>Run validation, scoring, tests, and any relevant packaging or benchmark steps.</li>
          <li>State whether the change affects seeded breadth, developed content, flagship assets, or certification posture.</li>
        </ol>
      </Panel>
      <Panel style={{ marginTop: 24 }}>
        <h2>Non-negotiables</h2>
        <ul>
          <li>No fake claims, logos, endorsements, or compatibility claims.</li>
          <li>No certification without benchmark coverage, score threshold, and manual review.</li>
          <li>No filler examples or weak rubrics that could apply to any skill in the repo.</li>
          <li>No autogenerated-sounding copy where sharper judgment is required.</li>
        </ul>
      </Panel>
    </SiteShell>
  );
}
